### ISSUE TITLE
Code stops at any function of PyDecoder

### ISSUE THREAD

**Issue by kqv1** [RomanArzumanyan/VALI#81]
Hello,
I am running VALI 3.2.11 in Windows 11, Python 3.12.4, Cuda 12.5

Any call to PyDecoder make the program to stop suddenly with no error message, while I can access functions of PyNvEncoder normally.

For example, when I use Debug Console to run TestEncoderBasic.test_encode_all_surfaces, 
the call to nvEnc.Format() return <PixelFormat.NV12: 3>
but the call to pyDec.Format() return [WinError 10054] An existing connection was forcibly closed by the remote host

    def test_encode_all_surfaces(self):
        with open("gt_files.json") as f:
            gtInfo = tc.GroundTruth(**json.load(f)["basic"])

        gpu_id = 0
        res = str(gtInfo.width) + "x" + str(gtInfo.height)
        encFrame = np.ndarray(shape=(0), dtype=np.uint8)

        pyDec = nvc.PyDecoder(gtInfo.uri, {}, gpu_id)
        nvEnc = nvc.PyNvEncoder(
            {
                "preset": "P4",
                "tuning_info": "high_quality",
                "codec": "h264",
                "profile": "high",
                "s": res,
                "bitrate": "1M",
            },
            gpu_id,
        )

        print(nvEnc.Format())
        print(pyDec.Format())

Please help,

**Comment by RomanArzumanyan** [comment]
Hi @kqv1 

I can reproduce the same issue locally. Will update you as I find something.

**Comment by RomanArzumanyan** [comment]
Hi @kqv1 

This one was easy. Error was cause by `memset` over the `std::map`.

It also turned out that `PyDecoder` unit test are not actually run under Windows in CI. Hence the Windows CI testing pipeline is always green disregarding the actual results. That's how this bug slipped into the codebase.

I need to make CI tests work under Windows but it no longer affects this very issue. I've tested decode sample on my Windows laptop and it works fine. Please check out `v.3.2.13`.

Closing this issue as completed, please LMK if the problem persists.
